# Generated by Django 3.1.7 on 2021-04-06 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='portfoilio_site',
            new_name='portfolio_site',
        ),
    ]
